#ifndef MIRATH_TCITH_API_H
#define MIRATH_TCITH_API_H

#include "mirath_parameters.h"

#define CRYPTO_PUBLICKEYBYTES MIRATH_PUBLIC_KEY_BYTES
#define CRYPTO_SECRETKEYBYTES MIRATH_SECRET_KEY_BYTES
#define CRYPTO_BYTES MIRATH_SIGNATURE_BYTES

#endif //MIRATH_TCITH_API_H
